a = input('digite algo: ')
print('O tipo primitivo dessa valor é ', type(a))
print('só tem espaços?', a.isspace())
print('é um unmero', a.isnumeric())
print('é alfabetico', a.isalpha())
print('é alfanúmerico', a.isalnum())
print('é alfanumerico,', a.isupper())
print('é minusculo', a.islower())
print('está em mausculo' , a.isupper())